language: java
jdk:
    - oraclejdk8
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5806f187d704525f5d20
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
